version: '3.9'

services:
  mongo:
    image: mongo
    container_name: meeting-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: meeting-backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/meeting-reservations
      - PORT=3001
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: meeting-frontend
    ports:
      - "5176:80"
    depends_on:
      - backend

volumes:
  mongo-data: